name: CI: Build and GitOps Deploy

on:
  push:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/nginx-app

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: terraform init
        working-directory: infra
      - run: terraform apply -auto-approve
        working-directory: infra

  build:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - uses: actions/checkout@v3

      - name: Set short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Build Docker Image
        run: docker build -t $REGISTRY/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }} apps/nginx-chart

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Image
        run: docker push $REGISTRY/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}

      - name: Update Helm Values with New Tag
        run: |
          sed -i.bak "s/tag: .*/tag: ${{ steps.vars.outputs.sha_short }}/" apps/nginx-chart/values.yaml

      - name: Commit & Push Helm Update
        run: |
          git config user.email "bot@ci.com"
          git config user.name "ci-bot"
          git add apps/nginx-chart/values.yaml
          git commit -m "Update image tag to ${{ steps.vars.outputs.sha_short }}"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
